### ISSUE TITLE
editorconfig

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/emacs.d#2]
https://github.com/editorconfig/editorconfig-emacs

**Comment by bcbcarl** [comment]
可以參考我的設定：
https://github.com/bcbcarl/emacs_config/blob/master/lisp/init-package.el

**Comment by wildskyf** [comment]
哦哦，謝謝卡羅

**Comment by wildskyf** [comment]
才發現一直沒有 enable...
`(editorconfig-mode 1)`
